services:
  php:
    container_name: php-fpm
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - database

  web:
    container_name: web
    image: nginx:1.25-alpine
    volumes:
      - ../.nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ..:/app
    ports:
      - 80:80
    depends_on:
      - php
      - database

  database:
    container_name: database
    image: mariadb:latest
    volumes:
      - data:/var/lib/mysql
      - ../.database:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

volumes:
  data: { name: database }
