services:
  php:
    container_name: php-fpm
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - database

  web:
    container_name: web
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ..:/app
    ports:
      - 80:80
    depends_on:
      - php
      - database

  database:
    container_name: database
    image: mariadb:latest
    volumes:
      - ../.database/data/:/var/lib/mysql
      - ../.database/:/app/config
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - :3306:3306
